[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["pyleotups*"]

[project]
name = "pyleotups"
version = "1.1.0"
description = "Automated Paleoclimate Data Extraction and Processing"
readme = "README.md"
authors = [
  { name = "Dhiren Oswal", email = "linkedearth@gmail.com" },
  { name = "Deborah Khider", email = "linkedearth@gmail.com" },
  { name = "Jay Pujara", email = "linkedearth@gmail.com" }
]
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.11"
dependencies = [
  "pandas",
  "requests",
  "numpy",
  "pybtex",
  "setuptools",
  "tqdm",
  "nbstripout",
  "xlrd",
  "openpyxl",
  "pangaeapy",
  "bibtexparser",
  "doi2bib"
]
keywords = ["pyleotups", "Table Understanding", "Data Analysis"]
urls = { Homepage = "https://github.com/LinkedEarth/pyleotups/pyleotups" }
