name: run pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout files in repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pyleotups
          environment-file: environment.yml
          python-version: "3.11"
          auto-activate-base: false

      - name: Conda list
        run: |
          conda activate pyleotups
          conda list

      - name: Test with pytest
        run: |
          conda activate pyleotups
          pytest pyleotups/tests -svv
